allowBuilds:
  core-js: true
  es5-ext: true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
overrides:
  '@huggingface/transformers': 4.0.0-next.6
onlyBuiltDependencies:
  - core-js
  - es5-ext
